spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  path: /var/logs/
  file: TacoCloud.log
  level:
    tacos: WARN

taco:
  orders:
    pageSize: 10

  discount:
    codes:
      abcdef: 10